### ISSUE TITLE
Executing '/rg setname' without arguments causes an error

### ISSUE THREAD

**Issue by Skulaurun** [SawFowl/RegionGuard#1]
## What I have installed on the server
- LocaleAPI: 2.3.0-S8.0.0
- RegionGuard: 1.5.3-S8.0.0
- SpongeForge: 1.16.5-36.2.5-8.1.0-RC1235
- Forge: 1.16.5-36.2.39

### Current behavior
When executing `/rg setname` without arguments an error occurs saying `Index 0 out of bounds for length 0`.

![image](https://user-images.githubusercontent.com/31413184/202753933-920695f3-7bac-4a35-a3d4-00349251f643.png)

### Expected behavior
Behavior similar to other commands like `/rg setowner`, `/rg setmessage`, etc.
For example: "You didn't specify a name."

![image](https://user-images.githubusercontent.com/31413184/202754340-72a846e7-8786-4eda-9252-64988fb6ccef.png)

**Comment by SawFowl** [comment]
Fixed https://ore.spongepowered.org/Semenkovsky_Ivan/RegionGuard/versions/1.5.5
I haven't tested the work of the fix much.

**Comment by Skulaurun** [comment]
It seems to work great, thanks!
As this issue is now fixed, I am closing it.
