### ISSUE TITLE
Предложение: портировать плагин на API7.

### ISSUE THREAD

**Issue by Artem-VV** [SawFowl/RegionGuard#2]
Добрый вечер. Будет ли ваш плагин когда-либо портирован на 7 API спонжа? Хотелось бы иметь возможность использовать привычную систему создания региона и на версии 1.12.2. Плагин, который там есть сейчас, ужасно неудобен.

**Comment by SawFowl** [comment]
Бесплатно я этого делать точно не буду, так как у меня полно других задач сейчас. В Ближайшее время планирую доделать CommandPack, в нем осталось реализовать экономику и голограммы с плейсхолдерами. После с выходом первой версии SpongeForge 1.19.4 мне будет необходимо перенести все свои популярные плагины на новую версию.  + в реале тоже дел хватает. Если вас устроит платный вариант, то за 5000 рублей я это реализую(без публикации даунгрейда на ORE,). Плагин не маленький, так что и цена маленькой не будет(вообще за такое обычно больше требуют, но я предпочитаю не жадничать). Там писать на API7 его по сути с нуля надо из-за отличий между API 7 и 8, по сути получится другой плагин с тем же названием и схожим функционалом. Обсудить детали при желании можно в дискорде https://discord.gg/4SMShjQ3Pe

**Comment by Artem-VV** [comment]
Спасибо за предложение, но откажусь - дорого.
Придется изучать другой пагин.
Спасибо за ответ.
