### ISSUE TITLE
Trust Command not recognizing "nicknames"

### ISSUE THREAD

**Issue by jcpt928** [SawFowl/RegionGuard#3]
Sponge 11.0 - 1.20.6
Offline mode [for good reasons].

"/rg trust playername permission" returns a "You must specific the player's nickname." response. (actually, any command using "playername" seems to provide the same response except "/rg limits playername".

**Comment by SawFowl** [comment]
I'll try to check it out soon. Does the error occur on vanilla server or Forge? There may be differences in their operation that I missed.

**Comment by jcpt928** [comment]
> I'll try to check it out soon. Does the error occur on vanilla server or Forge? There may be differences in their operation that I missed.

I'm 99% certain I'm running the Sponge server in Vanilla mode.

**Comment by jcpt928** [comment]
Also, we've now noticed that animal breeding no longer spawns baby animals - even in the default world region. Flags all set to "True" doesn't appear to resolve the issue.

**Comment by SawFowl** [comment]
I fixed the bugs. Download the latest versions of CommandPack and RegionGuard for API11.
